{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spine.fullname" . }}-gateway
  labels:
    {{- include "spine.gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "spine.gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
{{- end }}
